LineLength:
  Max: 200
StringLiterals:
  Enabled: false

Documentation:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false

LeadingCommentSpace:
  Enabled: false

NumericLiterals:
  Enabled: false

CaseIndentation:
  Enabled: false

MethodLength:
  Enabled: false

RedundantSelf:
  Enabled: false